<?php
require_once __DIR__ . '/config/bootstrap.php';
require_once __DIR__ . '/config/csrf.php';



// Check if the user is logged in
if (empty($_SESSION['user_id']) || empty($_SESSION['mfa_passed'])) {
    // Redirect to login page if not logged in
    header('Location: index.php');
    exit();
} else {
    // Get user data from session variables
    $user_id = $_SESSION['user_id'];
    $user_name = $_SESSION['user_name'];
    $user_email = $_SESSION['user_email'];
}

include 'vendor/sonata-project/google-authenticator/src/FixedBitNotation.php';
include 'vendor/sonata-project/google-authenticator/src/GoogleAuthenticatorInterface.php';
include 'vendor/sonata-project/google-authenticator/src/GoogleAuthenticator.php';
include 'vendor/sonata-project/google-authenticator/src/GoogleQrUrl.php';

$g = new \Sonata\GoogleAuthenticator\GoogleAuthenticator();

// Generate a new secret key if not already generated in session
if (empty($_SESSION['pending_2fa_secret'])) {

    $_SESSION['pending_2fa_secret'] = $g->generateSecret();
}
$new_secret = $_SESSION['pending_2fa_secret'];
// Prepare the SQL statement with placeholders
$query = "UPDATE user SET secret_key = ?, `2FA_enabled` = 1 WHERE id = ?";

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    if (!csrf_validate()) {
        exit('Security check failed');
    }

    $code = $_POST['code'] ?? '';

    if ($g->checkCode($new_secret, $code)) {

        // Create a prepared statement
        if ($stmt = mysqli_prepare($link, $query)) {

            // Bind parameters to the prepared statement
            mysqli_stmt_bind_param($stmt, "si", $new_secret, $user_id);

            // Execute the prepared statement
            if (mysqli_stmt_execute($stmt)) {
                unset($_SESSION['pending_2fa_secret']);
                // Update successful, redirect to profile
                header('Location: useraccount.php');
                exit();
            } else {

                echo "Error updating record: " . mysqli_error($link);
            }

            // Close the statement
            mysqli_stmt_close($stmt);
        } else {
            echo "Prepared statement creation failed";
        }
    }
}








// Display the QR code and form to enter the code from Authenticator app
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>2FA Setup</title>
</head>

<body>
    <?php
    $qrUrl = \Sonata\GoogleAuthenticator\GoogleQrUrl::generate(
        $user_email,               // account label in the authenticator app
        $new_secret,               // the TOTP secret in session
        'ClassRoomBookingSystem'   // issuer / app name
    );
    ?>
    <img src="<?= htmlspecialchars($qrUrl, ENT_QUOTES, 'UTF-8'); ?>" alt="Scan this QR">

    <h3>Enter the code generated by Authenticator App</h3>
    <form id="codeForm" method="POST" action="genqrcode.php">
        <?= csrf_field(); ?>
        <label for="codeInput">Enter code here: </label>
        <input type="text" name="code" id="codeInput" required>
        <input type="submit" value="Confirm">
    </form>
</body>

</html>