<?php
require_once __DIR__ . '/config/bootstrap.php';
require_once __DIR__ . '/config/csrf.php';

// If already fully authenticated, go to account
if (!empty($_SESSION['user_id']) && !empty($_SESSION['mfa_passed'])) {
  header('Location: useraccount.php');
  exit();
}
// Gate: must be logged in, 2FA enabled, and NOT yet passed
if (empty($_SESSION['user_id']) || empty($_SESSION['2FA_enabled']) || !empty($_SESSION['mfa_passed'])) {
  header('Location: index.php');
  exit();
}
?>
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>ClassRoomBooking</title>
  <link rel="stylesheet" href="style.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>
  <?php require_once __DIR__ . '/config/csrf.php';
  echo csrf_meta(); ?>
  <script src="assets/js/twofactor.js" defer></script>
</head>

<body>
  <div id="particles-js" style="position: absolute;height:100%;width:100%;margin:0;display:flex;"></div>
  <script src="https://cdn.jsdelivr.net/particles.js/2.0.0/particles.min.js"></script>
  <script src="https://threejs.org/examples/js/libs/stats.min.js"></script>

  <div class="navbar">
    <img onclick="location.href='index.php';" src='logo.png' alt="My" class="appLogo">
    <h1>ClassRoom Booking System</h1>
  </div>


  <form id="codeForm" class="login" style="align-items: center;flex-direction:column;justify-content: space-around;" autocomplete="one-time-code" novalidate>
    <div class="textClass" style="color: #3a3fc1;">
      <p>Enter the code generated by Google Authenticator App</p>
    </div>
    <img src="authenticator.svg" alt="" style="width: 40%; height: auto;max-width: 400px;">
    <div class="form-group" style="width: 80%;">
      <input placeholder=" " class="form-control" type="text" name="code" id="codeInput" inputmode="numeric" pattern="[0-9]*" maxlength="8" required />
      <label class="form-label" for="codeInput">Enter code here: </label>
    </div>
    <div style="width: 100%;display: flex;justify-content: space-evenly;align-items:center;flex-direction: column;">
      <button type="submit" value="Confirm" style="width: 50%;">Confirm</button>
    </div>
  </form>
</body>
<script src="particle.js"></script>
</html>