<?php
declare(strict_types=1);
require_once __DIR__ . '/config/bootstrap.php';
require_once __DIR__ . '/config/csrf.php';


// If already fully authenticated, go to account
if (!empty($_SESSION['user_id']) && !empty($_SESSION['mfa_passed'])) {
  header('Location: useraccount.php');
  exit();
}
// Gate: must be logged in, 2FA enabled, and NOT yet passed
if (empty($_SESSION['user_id']) || empty($_SESSION['2FA_enabled']) || !empty($_SESSION['mfa_passed'])) {
  header('Location: index.php');
  exit();
}
?>
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>ClassRoomBooking</title>
  <link rel="stylesheet" href="style.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>
  <?php require_once __DIR__ . '/config/csrf.php';
  echo csrf_meta(); ?>
  <script src="assets/js/twofactor.js" defer></script>
  <script src="https://cdn.jsdelivr.net/particles.js/2.0.0/particles.min.js" defer></script>
</head>

<body>
  <div id="particles-js"></div>


  <div class="navbar">
    <img id="appLogo" src='assets/images/logo.png' alt="My" class="appLogo">
    <h1>ClassRoom Booking System</h1>
  </div>


  <form id="codeForm" class="login twofactor-form" autocomplete="one-time-code" novalidate>
    <div class="textClass textClassBlue">
      <p>Enter the code generated by Google Authenticator App</p>
    </div>
    <img src="assets/images/authenticator.svg" alt="" class="authenticator-hero">
    <div class="form-group form-group-wide">
      <input placeholder=" " class="form-control" type="text" name="code" id="codeInput" inputmode="numeric" pattern="^[0-9]{6}$" maxlength="6" required />
      <label class="form-label" for="codeInput">Enter code here: </label>
    </div>
    <div class="buttons-column">
      <button type="submit" value="Confirm" class="btn-halfwidth">Confirm</button>
    </div>
  </form>
</body>
<script src="particle.js" defer></script>
</html>